// ===== AUTH =====
const DEFAULT_FB={apiKey:"AIzaSyB0Gc9SN7AgP0wVRq4S0OB91G4t5dePblY",authDomain:"mysf-837cd.firebaseapp.com",projectId:"mysf-837cd",storageBucket:"mysf-837cd.firebasestorage.app",messagingSenderId:"302347533776",appId:"1:302347533776:web:1491f9c5552a68ea478dd5"};
let _authHandled=false;
function initFirebase(){const c=ld("nt_firebase",null);const cfg=(c&&c.apiKey)?{apiKey:c.apiKey,authDomain:c.projectId+'.firebaseapp.com',projectId:c.projectId}:DEFAULT_FB;try{if(!firebase.apps.length)firebase.initializeApp(cfg);firebaseReady=true;firebase.auth().onAuthStateChanged(async u=>{if(u){currentUser=u;if(_authHandled)return;_authHandled=true;$('auth').classList.add('hidden');const hadData=ld("nt_setup",false);const loaded=await cloudLoad();if(!hadData&&loaded)sv("nt_setup",true);showApp();autoSync()}})}catch(e){console.warn('Firebase init error',e)}}
function initAuth(){initFirebase();$('aSkip').addEventListener('click',()=>{$('auth').classList.add('hidden');showApp()});
  $('gSign').addEventListener('click',()=>{if(!firebaseReady){$('aErr').textContent="Firebase non configure. Continue sans compte > Reglages > Firebase.";$('aErr').classList.add('show');return}const p=new firebase.auth.GoogleAuthProvider();p.addScope('https://www.googleapis.com/auth/fitness.activity.read');firebase.auth().signInWithPopup(p).then(async r=>{currentUser=r.user;if(r.credential)sv("nt_gtoken",r.credential.accessToken);$('auth').classList.add('hidden');const loaded=await cloudLoad();if(loaded)sv("nt_setup",true);showApp();autoSync()}).catch(e=>{if(e.code==='auth/popup-closed-by-user')return;$('aErr').textContent=e.message;$('aErr').classList.add('show')})})}
function showApp(){if(!ld("nt_setup",false)){$('ob').classList.remove('hidden');return}launch()}
function launch(){$('ob').classList.add('hidden');$('hdr').style.display='flex';$('mc').style.display='block';$('nav').style.display='flex';if(currentUser&&currentUser.photoURL){$('uAva').src=currentUser.photoURL;$('uAva').style.display='block'}setTheme(getTheme());updateBadge();renderHome()}

// ===== ONBOARDING =====
$('obGo').addEventListener('click',()=>{const w=parseFloat(($('obW').value||'75').replace(',','.'))||75,h=parseInt($('obH').value)||175,k=parseInt($('obK').value)||2200,ph=$('obPh').value;const prot=Math.round(w*2),lip=Math.round(w),gluc=Math.max(0,Math.round((k-prot*4-lip*9)/4)),fib=Math.round(14*k/1000);sv("nt_pw",w);sv("nt_height",h);sv("nt_phase",ph);sv("nt_targets",{kcal:k,prot,gluc,lip,fib});sv("nt_sg",10000);sv("nt_setup",true);launch()});
